In [13]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.naive_bayes import GaussianNB
import pickle

In [3]:
X, y = load_iris(return_X_y=True, as_frame=True)

In [5]:
colnames = X.columns
X_train = X.values

In [24]:
colnames

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [7]:
model = GaussianNB()

In [8]:
model.fit(X_train, y)

GaussianNB()

In [10]:
X_train[:3, :]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [12]:
model.predict([[3.7, 6.4, 1.6, 0.4]])

array([0])

In [14]:
with open('model.pickle', 'wb') as file:
    pickle.dump(model, file)

In [15]:
def train_iris_nb():
    """Train a GaussianNB model on iris dataset."""
    X, y_train = load_iris(return_X_y=True, as_frame=True)
    colnames = X.columns
    X_train = X.values
    model = GaussianNB()
    model.fit(X_train, y_train)
    return model

In [17]:
def dump_model(model_path, model):
    with open(model_path, 'wb') as file:
        pickle.dump(model, file)

In [18]:
def load_model(model_path):
    with open(model_path, 'rb') as file:
        model = pickle.load(file)
    return model

In [19]:
dump_model('model.pickle', model)

In [21]:
loaded_model = load_model('model.pickle')

In [23]:
loaded_model.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])